name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env: 
  NODE_VERSION: 16

jobs: 
  test:
    name: vitest-coverage
    runs-on: ubuntu-latest 
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Code Checkout
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: npm install

      - name: Get Coverage
        run: |
          SUMMARY="$(npm run-script test:vitest-coverage-ci | tail -2 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

      - name: Create Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 3eca25da4f1f1f04172a54cfd111b698
          filename: astro-template-coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}
          minColorRange: 0
          maxColorRange: 100
          valColorRange: ${{ env.COVERAGE }}.split('%')[0]
          namedLogo: vitest
