name: playwright

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env: 
  NODE_VERSION: 16

jobs:
  test:
    name: playwright-test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run-script test:playwright

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report.html
          path: tests/reports/playwright/
          retention-days: 10
